pygments:       true
permalink:      /:year/:month/:day/:title.html
paginate:       10

exclude:
    - README.md

title:          AzuWis Blog
url:            http://azuwis.github.com
feed:           /atom.xml
description:    "A Blog About Linux, Debian, GIT, Tips, Tutorials and More."
comment:        Blogging Like a Hacker

keywords:       Linux, Debian, GIT, Tips, Tutorials, Google, Blog, 博客

author:
    name:       AzuWis
    email:      azuwis@gmail.com
    twitter:    azuwis
    
disqus:
    id:         azuwis

feedsky:
    id:         azuwis

google:
    cse-cx:      009024607379464921389:urevm5phfaq
    cse-url:     /cse.html
    analytics:   UA-10843565-1

nav:
    - name:     Blog
      url:      /
      
    - name:     Apps
    
    - name:     Projects
        
    - name:     About
      url:      /about.html
