pygments:       true
permalink:      /:year/:month/:day/:title.html
paginate:       10

exclude:
    - README.md

title:          AzuWis Blog
url:            http://azuwis.github.com
feed:           /atom.xml
description:    "Advanced JavaScript techniques, tips on avoiding those nasty CSS bugs, and musings on technological progress."
comment:        Blogging Like a Hacker

keywords:       Linux, GIT, Tricks, Tutorials, Google, Blog, 博客

author:
    name:       AzuWis
    email:      azuwis@gmail.com
    twitter:    azuwis
    
disqus:
    id:         azuwis

feedsky:
    id:         azuwis

google:
    cse-cx:       009024607379464921389:urevm5phfaq
#    analytics:   UA-10843565-1

nav:
    - name:     Blog
      url:      /
      
    - name:     Apps
    
    - name:     Projects
        
    - name:     About
      url:      /about.html
