application: vi
version: 1
runtime: python
api_version: 1

handlers:
- url: (.*)/
  static_files: _site\1/index.html
  upload: _site/index.html

- url: /
  static_dir: _site

#- url: /.*
#  script: _scripts/main.py

skip_files:
- ^(?!_site/).*$
